subscribed_topics:
  [/kinect/rgb/image_raw, /left_camera/image, /right_camera/image]
published_topics: /vision/hazmat_alert
active_states: [EXPLORATION_RESCUE, IDENTIFICATION, SENSOR_HOLD, SENSOR_TEST, EXPLORATION_MAPPING]
