subscribed_topics:
  [/kinect/rgb/image_raw, /left_camera/image, /right_camera/image, /rpi2_primary/pi_camera_front/image, rpi2_secondary/pi_camera_rear/image]
published_topics: /vision/landoltc_alert
active_states: [EXPLORATION_RESCUE, IDENTIFICATION, SENSOR_HOLD, SENSOR_TEST, EXPLORATION_MAPPING]
