published_topic: /vision/victim_direction_alert
victim_debug_img_topic : /vision/victim_debug_img
victim_interpolated_depth_img_topic : /vision/interpolated_depth_img

subscribed_topic: [/vision/enhanced_holes]
