published_topic_names:  
  victim_alert : /vision/victim_direction_alert
  victim_debug_img : /vision/victim_debug_img
  victim_interpolated_depth_img : /vision/interpolated_depth_img
subscribed_topic_names:  
  enhanded_hole_alert : /vision/enhanced_holes
