subscribed_topics: [/kinect/rgb/image_raw, /rpi2_primary/pi_camera_front/image, rpi2_secondary/pi_camera_rear/image]
published_topics: /vision/obstacle_alert
active_states: [START_AUTONOMOUS, EXPLORATION_RESCUE, IDENTIFICATION, SENSOR_HOLD, SEMI_AUTONOMOUS, TELEOPERATED_LOCOMOTION, SENSOR_TEST, EXPLORATION_MAPPING]
