subscribed_topics:
  [/vision/synchronized/enhanced/image]
published_topics: /vision/obstacle_alert
active_states: [EXPLORATION_RESCUE, IDENTIFICATION, SEMI_AUTONOMOUS, TELEOPERATED_LOCOMOTION, SENSOR_TEST, EXPLORATION_MAPPING]
