camera_sensors: 
  - name: 'kinect'
    hfov: 58
    vfov: 45.0
    image_width: 640
    image_height: 480
  - name: 'left_camera'
    hfov: 58
    vfov: 45.0
    image_width: 640
    image_height: 480
  - name: 'right_camera'
    hfov: 58
    vfov: 45.0
    image_width: 640
    image_height: 480

